requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
env:
- LUET_NOLOCK=true
- LUET_YES=true
steps:
- curl https://get.mocaccino.org/luet/get_luet_root.sh | sh
- luet install repository/mocaccino-kernel
- luet install kernel/{{.Values.name}} && luet cleanup
- |
    kernel=$(ls /lib/modules | head -n1) && \ 
    emerge sys-kernel/gentoo-kernel sys-kernel/gentoo-sources && \
    cd /usr/src && rm -rfv linux && ln -s $kernel linux
