excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}

prelude:
- cp -rf package.use /etc/portage/
- cd /var/db/repos/gentoo/net-dialup/ppp && rm Manifest && ebuild ppp-2.4.8.ebuild digest

steps:
- USE="-vaapi" emerge -1 media-libs/mesa
- MAKEOPTS="-j1" emerge -1 dev-libs/nss
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- cp -rv xorg.conf.d/ /etc/X11/
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
- category: "layers"
  name: "sys-fs"
  version: ">=0"
