unpack: true
includes:
# Finalizer
- /patches$|/patches/.*

requires:
- category: "distro"
  name: "sabayon-desktop"
  version: ">=0.1"
- category: "distro"
  name: "sabayon-mate"
  version: ">=0.1"
- category: "distro"
  name: "sabayon-live"
  version: ">=0.5"

steps:
- mkdir /patches || true
- cp -rfv setup.sh /patches/live_mate_setup.sh
