excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
- TMPDIR=/var/tmp
prelude:
- cp -rf package.use /etc/portage/
steps:
- USE="-openldap" emerge -1 app-crypt/mit-krb5
- MAKEOPTS="-j1" emerge -1 sys-libs/talloc
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
