env:
- DESTDIR=/target
- SYSTEMD_UNITDIR=/lib/systemd/system

requires:
- category: "distro"
  name: "seed"
  version: ">=0.1"

entrypoint: "/bin/bash -c"
package_dir: /target
prelude:
- luet install vcs/git utils/ca-certificates development/make shells/bash
# Temporary use master branch instead of tag
- git clone https://github.com/Sabayon/sabayon-live.git /build
steps:
- echo $DESTDIR
- cd /build && /bin/bash -c 'make DESTDIR=/target SHELL=/bin/bash SYSTEMD_UNITDIR=/lib/systemd/system install'

# TODO: add labels for Marvin
