requires:
- category: "layer"
  name: "gentoo-portage"
  version: ">=0"
unpack: true
env:
- LUET_YES=true
- LUET_NOLOCK=true
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS={{ .Values.emerge.jobs }}

prelude:
- cp -rf package.use /etc/portage/
- cp -rf profile /etc/portage/
- cp -rf make.conf /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.license /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf patches/ /etc/portage/
- cp -rf bashrc /etc/portage/
# install entities
- rm /etc/shadow
- curl https://raw.githubusercontent.com/mudler/luet/master/contrib/config/get_luet_root.sh | sh
- luet install repository/os-commons
- luet install acct-group/adm acct-group/audio acct-group/cdrom acct-group/dialout acct-group/disk acct-group/input acct-group/kmem acct-group/kvm acct-group/lp acct-group/man acct-group/messagebus acct-group/nobody acct-group/polkitd acct-group/portage acct-group/render acct-group/root acct-group/sshd acct-group/systemd-coredump acct-group/systemd-journal acct-group/systemd-journal-remote acct-group/systemd-network acct-group/systemd-oom acct-group/systemd-resolve acct-group/systemd-timesync acct-group/tape acct-group/tty acct-group/unbound acct-group/users acct-group/utmp acct-group/video acct-group/wheel acct-user/man acct-user/messagebus acct-user/nobody acct-user/polkitd acct-user/portage acct-user/root acct-user/sshd acct-user/systemd-coredump acct-user/systemd-journal-remote acct-user/systemd-network acct-user/systemd-oom acct-user/systemd-resolve acct-user/systemd-timesync acct-user/unbound 
- luet cleanup
steps:
- eval 'emerge --unmerge dev-lang/python:3.9 || true'
- emerge -1 dev-libs/libgcrypt:0
- emerge -1 dev-libs/openssl net-misc/openssh -j $JOBS
- emerge -1D @system
- emerge -uDNv --with-bdeps=y --backtrack=100 --autounmask-keep-masks=y @world -j $JOBS
- emerge -t -j ${JOBS} {{ join " " .Values.emerge.packages }}
- emerge sys-apps/systemd sys-apps/dbus -j $JOBS
excludes:
- ^/etc/shadow
- ^/etc/os-release
- ^/etc/gshadow
- ^/etc/group
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/fstab
- ^/etc/passwd
- ^/etc/machineid
- ^/var/db/repos
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/cache/distfiles
- ^/var/log
- ^/var/cache/edb
- ^/usr/portage
- ^/sys
- ^/proc
- ^/luetbuild

# GCC split
- ^/etc/env.d/04gcc-x86_64-pc-linux-gnu
- ^/etc/ld.so.conf.d/05gcc-x86_64-pc-linux-gnu.conf
- ^/etc/env.d/gcc.*
- ^/usr/lib/debug/usr/lib/gcc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu.*
- ^/usr/bin/c\+\+.*
- ^/usr/bin/cc$
- ^/usr/bin/cpp.*
- ^/usr/bin/g\+\+.*
- ^/usr/bin/gcc.*
- ^/usr/bin/gccgo.*
- ^/usr/bin/go-.*
- ^/usr/bin/gofmt-.*
- ^/usr/bin/gcov.*
- ^/usr/bin/gfortran.*
- ^/usr/bin/x86_64-pc-linux-gnu-.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/lib/go.*
- ^/usr/lib64/go.*
- ^/usr/libexec/gcc.*
- ^/usr/share/gcc-data.*
- ^/usr/x86_64-pc-linux-gnu/gcc-bin.*
- ^/usr/lib/gcc
- ^/usr/lib/llvm.*
- ^/usr/lib/clang.*
- ^/etc/lvm.*

# devel
- ^/usr/include

# Emerge cache files
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
