excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
- ^/luetbuild
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
- LUET_YES=true
- LUET_NOLOCK=true
prelude:
- cp -rf package.use /etc/portage/
- curl https://get.mocaccino.org/luet/get_luet_root.sh | sh
- emerge -j ${JOBS} sys-kernel/gentoo-kernel sys-kernel/gentoo-sources
- luet install repository/mocaccino-kernel-stable
- luet install kernel/mocaccino-lts-sources && luet cleanup
# We use our kernel for compile modules
- cd /usr/src && eval 'rm linux || true' && ln -s linux-5.4.0-mocaccino linux
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
