unpack: true
requires:
- category: "distro"
  name: "seed"
  version: ">=0.1"
prelude:
- luet install vcs/git utils/ca-certificates
- git clone https://github.com/ivandavidov/minimal.git
- cd minimal && git checkout 9ac67c9b677396e70efbae239e137509f0372e40
steps:
- cp -rfv init minimal/src/minimal_rootfs/init
- cp -rfv motd minimal/src/minimal_rootfs/etc/motd
- cp -rfv 02_overlay.sh minimal/src/minimal_rootfs/etc/02_overlay.sh
- mkdir /mocaccino-init
- cp -rfv minimal/src/minimal_rootfs/* /mocaccino-init

package_dir: /mocaccino-init