unpack: true
image: "sabayon/base-amd64"
includes:
- /bin$|/bin/.*
- /dev$|/dev/.*
- /etc$
# TODO: Add /etc to config protect
- /etc$|/etc/.*

- /home$|/home/.*
- /lib$|/lib.*
- /media$|/media/.*
- /mnt$|/mnt/.*
- /opt$|/opt/.*
- /root$|/root/.*
- /run$|/run/.*
- /sbin$|/sbin/.*
- /usr$|/usr/.*
- /var$|/var/.*
