unpack: true
includes:
- /bin$|/bin/.*

- /dev$|/dev/.*
- /etc$
# TODO: Add /etc to config protect
- /etc$|/etc/.*

- /home$|/home/.*
- /lib$|/lib.*
- /media$|/media/.*
- /mnt$|/mnt/.*
- /opt$|/opt/.*
- /root$|/root/.*
- /run$|/run/.*
- /sbin$|/sbin/.*
- /usr$|/usr/.*
- /var$|/var/.*
steps:
- equo up
- > 
  ACCEPT_LICENSE=* equo i
  @gst-plugins
  @gst-plugins-extra
  @wireless
  app-admin/rigo
  app-arch/p7zip
  app-crypt/gnupg
  app-crypt/pinentry-qt5
  app-dicts/aspell-de
  app-dicts/aspell-en
  app-dicts/aspell-fr
  app-dicts/aspell-it
  app-dicts/aspell-nl
  app-dicts/aspell-pl
  app-dicts/myspell-de
  app-dicts/myspell-en
  app-dicts/myspell-es
  app-dicts/myspell-fr
  app-dicts/myspell-it
  app-dicts/myspell-nl
  app-misc/sabayon-greeter
  app-misc/calamares-sabayon
  app-misc/sabayon-skel
  app-misc/sabayon-version
  app-office/libreoffice
  games-misc/cowsay
  kde-apps/ark
  kde-apps/bomber
  kde-apps/bovo
  kde-apps/dolphin
  kde-apps/ffmpegthumbs
  kde-apps/gwenview
  kde-apps/k3b
  kde-apps/kamera
  kde-apps/kapman
  kde-apps/kcalc
  kde-apps/kcharselect
  kde-apps/kcolorchooser
  kde-plasma/kde-gtk-config
  kde-plasma/kwallet-pam
  kde-plasma/plasma-desktop
  kde-plasma/plasma-nm
  kde-plasma/plasma-meta
  kde-plasma/plasma-workspace
  dev-libs/libappindicator:2
  kde-apps/kde-l10n
  kde-apps/kdeadmin-meta
  kde-apps/kdenetwork-filesharing
  kde-apps/kdenlive
  kde-apps/kdf
  kde-apps/kdialog
  kde-apps/keditbookmarks
  kde-apps/kfind
  kde-apps/kfourinline
  kde-apps/kgpg
  kde-apps/killbots
  kde-apps/kipi-plugins
  kde-apps/kiriki
  kde-apps/klines
  kde-apps/kmag
  kde-apps/kmahjongg
  kde-apps/kmines
  kde-apps/kmousetool
  kde-apps/kmouth
  kde-apps/knetwalk
  kde-apps/kolf
  kde-apps/kollision
  kde-apps/konquest
  kde-apps/konsole
  kde-apps/kpat
  kde-apps/kreversi
  kde-apps/ksaneplugin
  kde-apps/kshisen
  kde-apps/kspaceduel
  kde-apps/ksquares
  kde-apps/ksudoku
  kde-apps/kubrick
  kde-apps/kwalletmanager
  kde-apps/kwrite
  kde-apps/libkcddb
  kde-apps/libkcompactdisc
  kde-apps/libkdcraw
  kde-apps/libkdegames
  kde-apps/libkexiv2
  kde-apps/libkipi
  kde-apps/libkmahjongg
  kde-apps/libkonq
  kde-apps/libksane
  kde-apps/okular
  kde-apps/plasma-apps
  kde-apps/print-manager
  kde-apps/spectacle
  kde-apps/svgpart
  kde-apps/thumbnailers
  kde-apps/yakuake
  kde-frameworks/oxygen-icons
  kde-misc/kio-gdrive
  kde-misc/magneto-kde
  kde-misc/skanlite
  media-libs/libdvdcss
  media-libs/libdvdnav
  media-libs/libdvdread
  media-plugins/alsa-plugins
  media-sound/clementine
  media-video/vlc
  net-dialup/ppp
  net-dialup/rp-pppoe
  net-fs/samba
  net-irc/konversation
  net-misc/networkmanager
  net-vpn/networkmanager-openvpn
  net-vpn/networkmanager-pptp
  net-vpn/networkmanager-vpnc
  net-misc/ntp
  net-print/cups
  net-wireless/bluez
  sys-firmware/bluez-firmware
  net-wireless/bluez-hcidump
  sys-apps/hdparm
  sys-apps/sdparm
  sys-apps/usbutils
  sys-auth/polkit
  sys-auth/polkit-qt
  sys-block/parted
  sys-block/partitionmanager
  sys-boot/os-prober
  sys-fs/dmraid
  sys-fs/ntfs3g
  sys-power/acpid
  sys-power/cpupower
  www-client/firefox
  x11-apps/xdm
  x11-libs/libva-intel-driver
  x11-libs/libva-vdpau-driver
  x11-misc/lightdm-slick-greeter
  x11-misc/xvkbd
  x11-themes/sabayon-artwork-core
  x11-themes/sabayon-artwork-extra
  x11-themes/sabayon-artwork-grub
  x11-themes/sabayon-artwork-lightdm-slick-greeter
  x11-themes/sound-theme-freedesktop
  x11-themes/xcursor-themes
  x11-wm/twm

- equo cleanup
- cp /etc/shadow /etc/shadow.defaults
- cp /etc/passwd /etc/passwd.defaults
- cp /etc/group /etc/group.defaults
- rm /var/log/entropy/entropy.log || true
requires:
- category: "distro"
  name: "sabayon-minimal-x"
  version: ">=0.1"
