excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
prelude:
- cp -rf package.use /etc/portage/
steps:
- mkdir -p /var/lib/sddm/.config
- touch /var/lib/sddm/.config/.keep
- chown -R sddm:sddm /var/lib/sddm
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- etc-update -q --automode -5
requires:
- category: "layers"
  name: "qt"
  version: ">=0"
- category: "apps"
  name: "vlc"
  version: ">=0"
