unpack: true
includes:
- /bin$|/bin/.*

- /dev$|/dev/.*
- /etc$
# We need to skip hostname \ hosts and resolv.conf (so the package can be also consumed in containers)
# For such setup prefer finalizer steps
# Explictly listing what we want from etc
# tar -tvf build/sabayon-desktop-*.package.tar.gz| grep etc/ | awk '{ print $6 }'
# Shadow, group stripped
- /etc/
- /etc/._cfg0000_hosts
- /etc/DIR_COLORS
- /etc/NetworkManager/
- /etc/NetworkManager/.*
- /etc/OpenCL/
- /etc/OpenCL/vendors/
- /etc/OpenCL/vendors/mesa.icd
- /etc/UPower/
- /etc/UPower/UPower.conf
- /etc/X11/
- /etc/X11/Sessions/
- /etc/X11/Sessions/Xsession
- /etc/X11/Sessions/fluxbox
- /etc/X11/Xresources
- /etc/X11/chooser.sh
- /etc/X11/startDM.sh
- /etc/X11/xdm/
- /etc/X11/xdm/Xaccess
- /etc/X11/xdm/Xresources
- /etc/X11/xdm/Xservers
- /etc/X11/xdm/xdm-config
- /etc/X11/xinit/
- /etc/X11/xinit/xinitrc
- /etc/X11/xinit/xinitrc.d/
- /etc/X11/xinit/xinitrc.d/00-xhost
- /etc/X11/xinit/xinitrc.d/40-libcanberra-gtk-module
- /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
- /etc/X11/xinit/xinitrc.d/80-dbus
- /etc/X11/xinit/xinput.d/
- /etc/X11/xinit/xinput.d/ibus.conf
- /etc/X11/xinit/xserverrc
- /etc/X11/xorg.conf.d/
- /etc/X11/xorg.conf.d/20opengl.conf
- /etc/X11/xsm/
- /etc/X11/xsm/system.xsm
- /etc/alsa/
- /etc/alsa/conf.d/
- /etc/alsa/conf.d/10-rate-lav.conf
- /etc/alsa/conf.d/10-samplerate.conf
- /etc/alsa/conf.d/10-speexrate.conf
- /etc/alsa/conf.d/50-jack.conf
- /etc/alsa/conf.d/50-pulseaudio.conf
- /etc/alsa/conf.d/51-pulseaudio-probe.conf
- /etc/alsa/conf.d/60-a52-encoder.conf
- /etc/alsa/conf.d/60-speex.conf
- /etc/alsa/conf.d/60-upmix.conf
- /etc/alsa/conf.d/60-vdownmix.conf
- /etc/alsa/conf.d/98-usb-stream.conf
- /etc/alsa/conf.d/99-pulseaudio-default.conf.example
- /etc/anacrontab
- /etc/atmsigd.conf
- /etc/avahi/
- /etc/avahi/avahi-autoipd.action
- /etc/avahi/avahi-daemon.conf
- /etc/avahi/avahi-dnsconfd.action
- /etc/avahi/hosts
- /etc/avahi/services/
- /etc/avahi/services/sftp-ssh.service
- /etc/avahi/services/ssh.service
- /etc/bash/
- /etc/bash/bash_logout
- /etc/bash/bashrc
- /etc/bash/bashrc.d/
- /etc/bash/bashrc.d/.keep_app-shells_bash-0
- /etc/bindresvport.blacklist
- /etc/binfmt.d/
- /etc/binfmt.d/.keep_sys-apps_systemd-0
- /etc/bluetooth/
- /etc/bluetooth/input.conf
- /etc/bluetooth/main.conf
- /etc/bluetooth/network.conf
- /etc/ca-certificates/
- /etc/ca-certificates/update.d/
- /etc/ca-certificates.conf
- /etc/calamares/
- /etc/calamares/*
- /etc/conf.d/
- /etc/conf.d/.*
- /etc/cron.d/
- /etc/cron.d/0hourly
- /etc/cron.daily/
- /etc/cron.daily/.keep_sys-process_cronbase-0
- /etc/cron.daily/man-db
- /etc/cron.deny
- /etc/cron.hourly/
- /etc/cron.hourly/.keep_sys-process_cronbase-0
- /etc/cron.hourly/0anacron
- /etc/cron.monthly/
- /etc/cron.monthly/.keep_sys-process_cronbase-0
- /etc/cron.weekly/
- /etc/cron.weekly/.keep_sys-process_cronbase-0
- /etc/cron.weekly/mdadm
- /etc/crontab
- /etc/csh.env
- /etc/cups/
- /etc/cups/client.conf
- /etc/cups/cups-browsed.conf
- /etc/cups/cups-files.conf
- /etc/cups/cups-files.conf.default
- /etc/cups/cupsd.conf
- /etc/cups/interfaces/
- /etc/cups/interfaces/.keep_net-print_cups-0
- /etc/cups/ppd/
- /etc/cups/ppd/.keep_net-print_cups-0
- /etc/cups/snmp.conf
- /etc/cups/snmp.conf.default
- /etc/cups/ssl/
- /etc/cups/ssl/.keep_net-print_cups-0
- /etc/dbus-1/
- /etc/dbus-1/.*
- /etc/dconf/
- /etc/dconf/db/
- /etc/dconf/db/ibus.d/
- /etc/dconf/db/ibus.d/00-upstream-settings
- /etc/dconf/profile/
- /etc/dconf/profile/ibus
- /etc/default/
- /etc/default/grub
- /etc/default/mdadm
- /etc/default/useradd
- /etc/dhcp/
- /etc/dhcp/dhclient.conf
- /etc/dhcp/dhcpd.conf
- /etc/dispatch-conf.conf
- /etc/dmtab
- /etc/dnsmasq.conf
- /etc/dnssec/
- /etc/dnssec/icannbundle.pem
- /etc/dnssec/root-anchors.p7s
- /etc/dnssec/root-anchors.txt
- /etc/dnssec/root-anchors.xml
- /etc/dracut.conf
- /etc/dracut.conf.d/
- /etc/dracut.conf.d/99-sabayon.conf
- /etc/e2fsck.conf
- /etc/e2scrub.conf
- /etc/entropy/
- /etc/entropy/.*
- /etc/env.d/
- /etc/env.d/.*
- /etc/environment
- /etc/etc-update.conf
- /etc/filesystems
- /etc/fonts/
- /etc/fonts/.*
- /etc/fstab
- /etc/fuse.conf
- /etc/gai.conf
- /etc/gentoo-release
- /etc/geoclue/
- /etc/geoclue/geoclue.conf
- /etc/gpm/
- /etc/gpm/gpm-root.conf
- /etc/gpm/gpm-syn.conf
- /etc/gpm/gpm-twiddler.conf
- /etc/group.defaults
- /etc/group-
- /etc/grub.d/
- /etc/grub.d/00_header
- /etc/grub.d/10_linux
- /etc/grub.d/20_linux_xen
- /etc/grub.d/30_os-prober
- /etc/grub.d/40_custom
- /etc/grub.d/41_custom
- /etc/grub.d/README
- /etc/gshadow.defaults
- /etc/gtk-2.0/
- /etc/gtk-2.0/im-multipress.conf
- /etc/gtk-3.0/
- /etc/gtk-3.0/im-multipress.conf
- /etc/gtk-3.0/settings.ini
- /etc/home/
- /etc/home/sabayonuser/
- /etc/home/sabayonuser/.local/
- /etc/home/sabayonuser/.local/share/
- /etc/home/sabayonuser/.local/share/gvfs-metadata/
- /etc/home/sabayonuser/.local/share/gvfs-metadata/home
- /etc/home/sabayonuser/.local/share/gvfs-metadata/root
- /etc/host.conf
- /etc/hostname
- /etc/hosts
- /etc/hosts#entropy_new_55859
- /etc/hosts.allow
- /etc/hosts.atm
- /etc/init.d/
- /etc/init.d/NetworkManager
- /etc/init.d/avahi-daemon
- /etc/init.d/avahi-dnsconfd
- /etc/init.d/bluetooth
- /etc/init.d/busybox-ntpd
- /etc/init.d/busybox-watchdog
- /etc/init.d/cpupower
- /etc/init.d/cronie
- /etc/init.d/cups-browsed
- /etc/init.d/cupsd
- /etc/init.d/dbus
- /etc/init.d/device-mapper
- /etc/init.d/dhcpd
- /etc/init.d/dhcrelay
- /etc/init.d/dhcrelay6
- /etc/init.d/dmcrypt
- /etc/init.d/dmeventd
- /etc/init.d/dnsmasq
- /etc/init.d/fuse
- /etc/init.d/gpm
- /etc/init.d/ip6tables
- /etc/init.d/iptables
- /etc/init.d/kmod-static-nodes
- /etc/init.d/lvm
- /etc/init.d/lvm-monitoring
- /etc/init.d/lvmetad
- /etc/init.d/lvmpolld
- /etc/init.d/mdadm
- /etc/init.d/mdraid
- /etc/init.d/mit-krb5kadmind
- /etc/init.d/mit-krb5kdc
- /etc/init.d/mit-krb5kpropd
- /etc/init.d/nscd
- /etc/init.d/nullmailer
- /etc/init.d/ofono
- /etc/init.d/pciparm
- /etc/init.d/pcscd
- /etc/init.d/pppoe-server
- /etc/init.d/pwcheck
- /etc/init.d/pydoc-2.7
- /etc/init.d/pydoc-3.6
- /etc/init.d/rsyncd
- /etc/init.d/saslauthd
- /etc/init.d/slapd
- /etc/init.d/sshd
- /etc/init.d/udev
- /etc/init.d/udev-settle
- /etc/init.d/udev-trigger
- /etc/init.d/unbound
- /etc/init.d/xdm
- /etc/init.d/xdm-setup
- /etc/init.d/zfs-import
- /etc/init.d/zfs-mount
- /etc/init.d/zfs-share
- /etc/init.d/zfs-zed
- /etc/inputrc
- /etc/iproute2/
- /etc/iproute2/bpf_pinning
- /etc/iproute2/ematch_map
- /etc/iproute2/group
- /etc/iproute2/nl_protos
- /etc/iproute2/rt_dsfield
- /etc/iproute2/rt_protos
- /etc/iproute2/rt_realms
- /etc/iproute2/rt_scopes
- /etc/iproute2/rt_tables
- /etc/irssi.conf
- /etc/issue
- /etc/issue.logo
- /etc/kernel/
- /etc/kernel/install.d/
- /etc/kernel/postinst.d/
- /etc/kernel/postinst.d/.keep_sys-apps_debianutils-0
- /etc/krb5.conf.example
- /etc/ld.so.cache
- /etc/ld.so.conf
- /etc/ld.so.conf.d/
- /etc/ld.so.conf.d/05gcc-x86_64-pc-linux-gnu.conf
- /etc/ldap.conf.sudo
- /etc/libblockdev/
- /etc/libblockdev/conf.d/
- /etc/libblockdev/conf.d/00-default.cfg
- /etc/libnl/
- /etc/libnl/classid
- /etc/libnl/pktloc
- /etc/locale.conf
- /etc/locale.gen
- /etc/localtime
- /etc/login.defs
- /etc/logrotate.d/
- /etc/logrotate.d/dnsmasq
- /etc/logrotate.d/dracut
- /etc/logrotate.d/elog-save-summary
- /etc/logrotate.d/entropy
- /etc/logrotate.d/rsyncd
- /etc/lsb-release
- /etc/lvm/
- /etc/lvm/lvm.conf
- /etc/lvm/lvmlocal.conf
- /etc/lvm/profile/
- /etc/lvm/profile/cache-mq.profile
- /etc/lvm/profile/cache-smq.profile
- /etc/lvm/profile/command_profile_template.profile
- /etc/lvm/profile/lvmdbusd.profile
- /etc/lvm/profile/metadata_profile_template.profile
- /etc/lvm/profile/thin-generic.profile
- /etc/lvm/profile/thin-performance.profile
- /etc/lxdm/
- /etc/lxdm/LoginReady
- /etc/lxdm/PostLogin
- /etc/lxdm/PostLogout
- /etc/lxdm/PreLogin
- /etc/lxdm/PreReboot
- /etc/lxdm/PreShutdown
- /etc/lxdm/Xsession
- /etc/lxdm/lxdm.conf
- /etc/machine-id
- /etc/mail/
- /etc/mail/aliases
- /etc/mailcap
- /etc/make.profile
- /etc/man_db.conf
- /etc/mdadm.conf
- /etc/mime.types
- /etc/mke2fs.conf
- /etc/modprobe.d/
- /etc/modprobe.d/aliases.conf
- /etc/modprobe.d/blacklist.conf
- /etc/modprobe.d/i386.conf
- /etc/modprobe.d/ppp.conf
- /etc/modules-load.d/
- /etc/modules-load.d/.keep_sys-apps_systemd-0
- /etc/mtab
- /etc/nanorc
- /etc/netconfig
- /etc/networks
- /etc/nscd.conf
- /etc/nsswitch.conf
- /etc/nullmailer/
- /etc/nullmailer/remotes
- /etc/ofono/
- /etc/ofono/phonesim.conf
- /etc/openldap/
- /etc/openldap/DB_CONFIG.example
- /etc/openldap/ldap.conf
- /etc/openldap/ldap.conf.default
- /etc/openldap/schema/
- /etc/openldap/schema/README
- /etc/openldap/schema/collective.ldif
- /etc/openldap/schema/collective.schema
- /etc/openldap/schema/corba.ldif
- /etc/openldap/schema/corba.schema
- /etc/openldap/schema/core.ldif
- /etc/openldap/schema/core.schema
- /etc/openldap/schema/cosine.ldif
- /etc/openldap/schema/cosine.schema
- /etc/openldap/schema/dhcp.schema
- /etc/openldap/schema/duaconf.ldif
- /etc/openldap/schema/duaconf.schema
- /etc/openldap/schema/dyngroup.ldif
- /etc/openldap/schema/dyngroup.schema
- /etc/openldap/schema/inetorgperson.ldif
- /etc/openldap/schema/inetorgperson.schema
- /etc/openldap/schema/java.ldif
- /etc/openldap/schema/java.schema
- /etc/openldap/schema/kerberos.schema
- /etc/openldap/schema/misc.ldif
- /etc/openldap/schema/misc.schema
- /etc/openldap/schema/nis.ldif
- /etc/openldap/schema/nis.schema
- /etc/openldap/schema/openldap.ldif
- /etc/openldap/schema/openldap.schema
- /etc/openldap/schema/pmi.ldif
- /etc/openldap/schema/pmi.schema
- /etc/openldap/schema/ppolicy.ldif
- /etc/openldap/schema/ppolicy.schema
- /etc/openldap/schema/rfc2307bis.schema
- /etc/openldap/schema/sudo.schema
- /etc/openldap/slapd.conf
- /etc/openldap/slapd.conf.default
- /etc/openldap/slapd.ldif
- /etc/openldap/slapd.ldif.default
- /etc/os-release
- /etc/pam.d/
- /etc/pam.d/.*
- /etc/papersize
- /etc/passwd
- /etc/passwd-
- /etc/pkcs11/
- /etc/pkcs11/pkcs11.conf.example
- /etc/plymouth/
- /etc/plymouth/plymouthd.conf
- /etc/polkit-1/
- /etc/polkit-1/rules.d/
- /etc/polkit-1/rules.d/50-default.rules
- /etc/portage
- /etc/portage-gentoo/
- /etc/portage-gentoo/make.conf
- /etc/portage-gentoo/make.profile
- /etc/portage-gentoo/package.keywords/
- /etc/portage-gentoo/package.keywords/00-sabayon.package.keywords
- /etc/portage-gentoo/package.use/
- /etc/portage-gentoo/package.use/00-sabayon.package.use
- /etc/portage-gentoo/repo.postsync.d/
- /etc/portage-gentoo/repo.postsync.d/example
- /etc/portage-gentoo/repos.conf/
- /etc/portage-gentoo/repos.conf/gentoo.conf
- /etc/portage-gentoo/repos.conf/layman.conf
- /etc/portage-gentoo/savedconfig/
- /etc/portage-gentoo/savedconfig/sys-apps/
- /etc/portage-gentoo/savedconfig/sys-apps/busybox-1.30.1
- /etc/ppp/
- /etc/ppp/chap-secrets
- /etc/ppp/chap-secrets.example
- /etc/ppp/firewall-masq
- /etc/ppp/firewall-standalone
- /etc/ppp/ip-down
- /etc/ppp/ip-down.d/
- /etc/ppp/ip-down.d/30-wins.sh
- /etc/ppp/ip-down.d/40-dns.sh
- /etc/ppp/ip-down.d/50-initd.sh
- /etc/ppp/ip-up
- /etc/ppp/ip-up.d/
- /etc/ppp/ip-up.d/30-wins.sh
- /etc/ppp/ip-up.d/40-dns.sh
- /etc/ppp/ip-up.d/50-initd.sh
- /etc/ppp/ipv6-down
- /etc/ppp/ipv6-up
- /etc/ppp/options
- /etc/ppp/pap-secrets
- /etc/ppp/pap-secrets.example
- /etc/ppp/peers/
- /etc/ppp/plugins/
- /etc/ppp/plugins/README
- /etc/ppp/plugins/rp-pppoe.so
- /etc/ppp/pppoe-server-options
- /etc/ppp/pppoe.conf
- /etc/ppp/radius/
- /etc/ppp/radius/dictionary
- /etc/ppp/radius/dictionary.ascend
- /etc/ppp/radius/dictionary.compat
- /etc/ppp/radius/dictionary.merit
- /etc/ppp/radius/dictionary.microsoft
- /etc/ppp/radius/issue
- /etc/ppp/radius/port-id-map
- /etc/ppp/radius/radiusclient.conf
- /etc/ppp/radius/realms
- /etc/ppp/radius/servers
- /etc/prelink.conf.d/
- /etc/prelink.conf.d/nss.conf
- /etc/profile
- /etc/profile.d/
- /etc/profile.d/.keep
- /etc/profile.d/gawk.csh
- /etc/profile.d/gawk.sh
- /etc/profile.env
- /etc/protocols
- /etc/pulse/
- /etc/pulse/client.conf
- /etc/pulse/daemon.conf
- /etc/pulse/default.pa
- /etc/pulse/system.pa
- /etc/python-exec/
- /etc/python-exec/python-exec.conf
- /etc/rc.conf
- /etc/request-key.conf
- /etc/request-key.d/
- /etc/resolv.conf
- /etc/rmt
- /etc/rpc
- /etc/rsyncd.conf
- /etc/runlevels/
- /etc/runlevels/boot/
- /etc/runlevels/boot/opentmpfiles-setup
- /etc/runlevels/sysinit/
- /etc/runlevels/sysinit/kmod-static-nodes
- /etc/runlevels/sysinit/opentmpfiles-dev
- /etc/runlevels/sysinit/udev
- /etc/runlevels/sysinit/udev-trigger
- /etc/sabayon/
- /etc/sabayon/sabayon-welcome-loader.desktop
- /etc/sabayon-pkglist
- /etc/sabayon-py3-was-set
- /etc/sabayon-release
- /etc/sandbox.conf
- /etc/sandbox.d/
- /etc/sandbox.d/00default
- /etc/sandbox.d/10openssl
- /etc/sandbox.d/15man-db
- /etc/sandbox.d/37fontconfig
- /etc/sasl2/
- /etc/sasl2/.keep_dev-libs_cyrus-sasl-2
- /etc/sasl2/sasldb2
- /etc/security/
- /etc/security/access.conf
- /etc/security/capability.conf
- /etc/security/group.conf
- /etc/security/limits.conf
- /etc/security/limits.d/
- /etc/security/limits.d/00-sabayon-anti-fork-bomb.conf
- /etc/security/limits.d/40-realtime-base.conf
- /etc/security/namespace.conf
- /etc/security/namespace.d/
- /etc/security/namespace.init
- /etc/security/pam_env.conf
- /etc/security/pwquality.conf
- /etc/security/time.conf
- /etc/services
- /etc/sgml/
- /etc/sgml/catalog
- /etc/sgml/sgml-docbook.cat
- /etc/sgml/sgml-ent.cat
- /etc/sgml/sgml.conf
- /etc/sgml/xml-docbook-4.5.cat
- /etc/shadow.defaults
- /etc/shells
- /etc/skel/
- /etc/skel/.*
- /etc/slsh.rc
- /etc/ssh/
- /etc/ssh/moduli
- /etc/ssh/ssh_config
- /etc/ssh/sshd_config
- /etc/ssl/
- /etc/ssl/certs/.*
- /etc/ssl/ct_log_list.cnf
- /etc/ssl/ct_log_list.cnf.dist
- /etc/ssl/misc/
- /etc/ssl/misc/CA.pl
- /etc/ssl/misc/tsget
- /etc/ssl/misc/tsget.pl
- /etc/ssl/openssl.cnf
- /etc/ssl/openssl.cnf.dist
- /etc/ssl/private/
- /etc/ssl/private/.keep_dev-libs_openssl-0
- /etc/sudoers
- /etc/sudoers.d/
- /etc/sudoers.d/zfs
- /etc/sudoers.dist
- /etc/sysctl.conf
- /etc/sysctl.d/
- /etc/sysctl.d/99-sysctl.conf
- /etc/system-release
- /etc/systemd/
- /etc/systemd/coredump.conf
- /etc/systemd/journald.conf
- /etc/systemd/logind.conf
- /etc/systemd/network/
- /etc/systemd/networkd.conf
- /etc/systemd/ntp-units.d/
- /etc/systemd/ntp-units.d/.keep_sys-apps_systemd-0
- /etc/systemd/resolved.conf
- /etc/systemd/sleep.conf
- /etc/systemd/system/
- /etc/systemd/system/cpupower-frequency-set.service.d/
- /etc/systemd/system/cpupower-frequency-set.service.d/00gentoo.conf
- /etc/systemd/system/dhcrelay4.service.d/
- /etc/systemd/system/dhcrelay4.service.d/00gentoo.conf
- /etc/systemd/system/dhcrelay6.service.d/
- /etc/systemd/system/dhcrelay6.service.d/00gentoo.conf
- /etc/systemd/system/getty.target.wants/
- /etc/systemd/system/multi-user.target.wants/
- /etc/systemd/system/slapd.service.d/
- /etc/systemd/system/slapd.service.d/00gentoo.conf
- /etc/systemd/system.conf
- /etc/systemd/timesyncd.conf
- /etc/systemd/user/
- /etc/systemd/user/.keep_sys-apps_systemd-0
- /etc/systemd/user.conf
- /etc/terminfo/
- /etc/terminfo/a/
- /etc/terminfo/a/ansi
- /etc/terminfo/d/
- /etc/terminfo/d/dumb
- /etc/terminfo/l/
- /etc/terminfo/l/linux
- /etc/terminfo/r/
- /etc/terminfo/r/rxvt
- /etc/terminfo/r/rxvt-256color
- /etc/terminfo/r/rxvt-unicode
- /etc/terminfo/r/rxvt-unicode-256color
- /etc/terminfo/s/
- /etc/terminfo/s/screen
- /etc/terminfo/s/screen-256color
- /etc/terminfo/s/screen.xterm-256color
- /etc/terminfo/v/
- /etc/terminfo/v/vt100
- /etc/terminfo/v/vt102
- /etc/terminfo/v/vt200
- /etc/terminfo/v/vt220
- /etc/terminfo/v/vt52
- /etc/terminfo/x/
- /etc/terminfo/x/xterm
- /etc/terminfo/x/xterm-256color
- /etc/terminfo/x/xterm-color
- /etc/timezone
- /etc/tmpfiles.d/
- /etc/tmpfiles.d/.keep_sys-apps_systemd-0
- /etc/udev/
- /etc/udev/hwdb.bin
- /etc/udev/hwdb.d/
- /etc/udev/hwdb.d/.keep_sys-apps_systemd-0
- /etc/udev/rules.d/
- /etc/udev/rules.d/.keep_sys-apps_systemd-0
- /etc/udev/udev.conf
- /etc/udhcpd.conf
- /etc/udisks2/
- /etc/udisks2/udisks2.conf
- /etc/unbound/
- /etc/unbound/unbound.conf
- /etc/unbound/var/
- /etc/unbound/var/.keep_net-dns_unbound-0
- /etc/usb_modeswitch.conf
- /etc/usb_modeswitch.d/
- /etc/vdpau_wrapper.cfg
- /etc/wgetrc
- /etc/wireless-regdb/
- /etc/wireless-regdb/pubkeys/
- /etc/wireless-regdb/pubkeys/.keep_net-wireless_crda-0
- /etc/wireless-regdb/pubkeys/sforshee.key.pub.pem
- /etc/wpa_supplicant/
- /etc/wpa_supplicant/wpa_cli.sh
- /etc/xattr.conf
- /etc/xdg/
- /etc/xdg/accept-languages.codes
- /etc/xdg/autostart/
- /etc/xdg/autostart/at-spi-dbus-bus.desktop
- /etc/xdg/autostart/geoclue-demo-agent.desktop
- /etc/xdg/autostart/polkit-kde-authentication-agent-1.desktop
- /etc/xdg/autostart/pulseaudio.desktop
- /etc/xdg/kscreenlockerrc
- /etc/xdg/kshorturifilterrc
- /etc/xdg/menus/
- /etc/xdg/menus/applications-merged/
- /etc/xdg/menus/applications-merged/sabayon-sabayon.menu
- /etc/xdg/menus/applications.menu
- /etc/xdg/menus/kf5-applications.menu
- /etc/xdg/qtchooser/
- /etc/xdg/qtchooser/.keep_dev-qt_qtchooser-0
- /etc/xdg/qtchooser/5.conf
- /etc/xdg/qtchooser/default.conf
- /etc/xdg/qtchooser/qt5-x86_64-pc-linux-gnu.conf
- /etc/xdg/qtchooser/qt5.conf
- /etc/xdg/systemd/
- /etc/xdg/systemd/user
- /etc/xdg/ui/
- /etc/xdg/ui/ui_standards.rc
- /etc/xinetd.d/
- /etc/xinetd.d/rsyncd
- /etc/xml/
- /etc/xml/.keep_app-text_docbook-xml-dtd-4.5
- /etc/xml/catalog
- /etc/xml/docbook
- /etc/zfs/
- /etc/zfs/.*
- /usr/lib/environment.d/99-environment.conf
- /usr/share/factory/etc/
- /usr/share/factory/etc/nsswitch.conf
- /usr/share/factory/etc/pam.d/
- /usr/share/factory/etc/pam.d/other
- /usr/share/factory/etc/pam.d/system-auth
- /usr/share/terminfo/a/ansi
- /usr/share/terminfo/d/dumb
- /usr/share/terminfo/l/linux
- /usr/share/terminfo/r/rxvt
- /usr/share/terminfo/r/rxvt-256color
- /usr/share/terminfo/r/rxvt-unicode
- /usr/share/terminfo/r/rxvt-unicode-256color
- /usr/share/terminfo/s/screen
- /usr/share/terminfo/s/screen-256color
- /usr/share/terminfo/s/screen.xterm-256color
- /usr/share/terminfo/v/vt100
- /usr/share/terminfo/v/vt102
- /usr/share/terminfo/v/vt200
- /usr/share/terminfo/v/vt220
- /usr/share/terminfo/v/vt52
- /usr/share/terminfo/x/xterm
- /usr/share/terminfo/x/xterm-256color
- /usr/share/terminfo/x/xterm-color
- /var/lib/dbus/machine-id

- /home$|/home/.*
- /lib$|/lib.*
- /media$|/media/.*
- /mnt$|/mnt/.*
- /opt$|/opt/.*
- /root$|/root/.*
- /run$|/run/.*
- /sbin$|/sbin/.*
- /usr$|/usr/.*
- /var$|/var/.*
steps:
- equo up
- > 
  ACCEPT_LICENSE=* equo i @wireless 
  @fluxbox 
  app-misc/calamares-sabayon 
  app-text/pastebunz 
  lxde-base/lxdm 
  media-gfx/feh 
  net-dialup/ppp 
  net-dialup/rp-pppoe 
  net-irc/irssi 
  net-misc/tightvnc 
  sys-apps/usbutils 
  sys-block/parted 
  sys-boot/os-prober 
  sys-power/cpupower 
  sys-process/htop 
  www-client/midori 
  x11-themes/adwaita-icon-theme 
  x11-themes/sabayon-artwork-core 
  x11-themes/sabayon-artwork-grub  
  @X 
  app-arch/unrar 
  app-misc/sabayon-live 
  app-misc/sabayon-skel 
  media-fonts/dejavu 
  media-fonts/corefonts 
  media-libs/libtxc_dxtn 
  media-libs/mesa 
  sys-apps/lsb-release 
  sys-apps/usb_modeswitch 
  sys-apps/which 
  sys-process/htop 
  x11-apps/xhost 
  x11-apps/setxkbmap 
  x11-themes/equinox-themes 
  x11-themes/gtk-engines:2 
  x11-themes/hicolor-icon-theme 
  x11-themes/iottinka-artwork 
  x11-terms/xterm 
  x11-libs/libXxf86misc 
- equo cleanup
- cp /etc/shadow /etc/shadow.defaults
- cp /etc/passwd /etc/passwd.defaults
- cp /etc/gshadow /etc/gshadow.defaults
- cp /etc/group /etc/group.defaults
requires:
- category: "distro"
  name: "sabayon"
  version: "0.1"
