excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
- ^/luetbuild
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
- LUET_YES=true
- LUET_NOLOCK=true
prelude:
- cp -rf package.use /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- cp -r 10_linux /etc/grub.d/10_linux
- cp grub-default /etc/default/grub
requires:
- category: "layers"
  name: "X"
  version: ">=0"
- category: "layers"
  name: "sys-fs"
  version: ">=0"
