unpack: true
includes:
# Dbus, needed by systemd-logind to reach multi-user target ( equo q files sys-apps/dbus -q > dbus.txt ):
# - /etc$
# - /etc/X11$
# - /etc/X11/xinit
# - /etc/X11/xinit/xinitrc.d
# - /etc/X11/xinit/xinitrc.d/80-dbus
# - /etc/dbus-1
# - /etc/dbus-1/session.conf
# - /etc/dbus-1/session.d
# - /etc/dbus-1/session.d/.keep_sys-apps_dbus-0
# - /etc/dbus-1/system.conf
# - /etc/dbus-1/system.d
# - /etc/dbus-1/system.d/.keep_sys-apps_dbus-0
# - /etc/init.d
# - /etc/init.d/dbus
# - /lib$
# - /lib/systemd$
# - /lib/systemd/system$
# - /lib/systemd/system/dbus.service
# - /lib/systemd/system/dbus.socket
# - /lib/systemd/system/multi-user.target.wants
# - /lib/systemd/system/multi-user.target.wants/dbus.service
# - /lib/systemd/system/sockets.target.wants
# - /lib/systemd/system/sockets.target.wants/dbus.socket
# - /usr$
# - /usr/bin$
# - /usr/bin/dbus-cleanup-sockets
# - /usr/bin/dbus-daemon
# - /usr/bin/dbus-launch
# - /usr/bin/dbus-monitor
# - /usr/bin/dbus-run-session
# - /usr/bin/dbus-send
# - /usr/bin/dbus-test-tool
# - /usr/bin/dbus-update-activation-environment
# - /usr/bin/dbus-uuidgen
# - /usr/include$
# - /usr/include/dbus-1.0
# - /usr/include/dbus-1.0/dbus
# - /usr/include/dbus-1.0/dbus/dbus-address.h
# - /usr/include/dbus-1.0/dbus/dbus-bus.h
# - /usr/include/dbus-1.0/dbus/dbus-connection.h
# - /usr/include/dbus-1.0/dbus/dbus-errors.h
# - /usr/include/dbus-1.0/dbus/dbus-macros.h
# - /usr/include/dbus-1.0/dbus/dbus-memory.h
# - /usr/include/dbus-1.0/dbus/dbus-message.h
# - /usr/include/dbus-1.0/dbus/dbus-misc.h
# - /usr/include/dbus-1.0/dbus/dbus-pending-call.h
# - /usr/include/dbus-1.0/dbus/dbus-protocol.h
# - /usr/include/dbus-1.0/dbus/dbus-server.h
# - /usr/include/dbus-1.0/dbus/dbus-shared.h
# - /usr/include/dbus-1.0/dbus/dbus-signature.h
# - /usr/include/dbus-1.0/dbus/dbus-syntax.h
# - /usr/include/dbus-1.0/dbus/dbus-threads.h
# - /usr/include/dbus-1.0/dbus/dbus-types.h
# - /usr/include/dbus-1.0/dbus/dbus.h
# - /usr/lib$
# - /usr/lib/systemd
# - /usr/lib/systemd/user
# - /usr/lib/systemd/user/dbus.service
# - /usr/lib/systemd/user/dbus.socket
# - /usr/lib/systemd/user/sockets.target.wants
# - /usr/lib/systemd/user/sockets.target.wants/dbus.socket
# - /usr/lib/sysusers.d
# - /usr/lib/sysusers.d/dbus.conf
# - /usr/lib/tmpfiles.d
# - /usr/lib/tmpfiles.d/dbus.conf
# - /usr/lib32$
# - /usr/lib32/dbus-1.0$
# - /usr/lib32/dbus-1.0/include
# - /usr/lib32/dbus-1.0/include/dbus
# - /usr/lib32/dbus-1.0/include/dbus/dbus-arch-deps.h
# - /usr/lib32/libdbus-1.so
# - /usr/lib32/libdbus-1.so.3
# - /usr/lib32/libdbus-1.so.3.19.11
# - /usr/lib32/pkgconfig$
# - /usr/lib32/pkgconfig/dbus-1.pc
# - /usr/lib64$
# - /usr/lib64/cmake$
# - /usr/lib64/cmake/DBus1
# - /usr/lib64/cmake/DBus1/DBus1Config.cmake
# - /usr/lib64/cmake/DBus1/DBus1ConfigVersion.cmake
# - /usr/lib64/dbus-1.0$
# - /usr/lib64/dbus-1.0/include$
# - /usr/lib64/dbus-1.0/include/dbus
# - /usr/lib64/dbus-1.0/include/dbus/dbus-arch-deps.h
# - /usr/lib64/libdbus-1.so
# - /usr/lib64/libdbus-1.so.3
# - /usr/lib64/libdbus-1.so.3.19.11
# - /usr/lib64/pkgconfig$
# - /usr/lib64/pkgconfig/dbus-1.pc
# - /usr/libexec$
# - /usr/libexec/dbus-daemon-launch-helper
# - /usr/share$
# - /usr/share/dbus-1$
# - /usr/share/dbus-1/services$
# - /usr/share/dbus-1/services/.keep_sys-apps_dbus-0
# - /usr/share/dbus-1/session.conf
# - /usr/share/dbus-1/session.d
# - /usr/share/dbus-1/system-services
# - /usr/share/dbus-1/system.conf
# - /usr/share/dbus-1/system.d
# - /usr/share/doc$
# - /usr/share/doc/dbus-1.12.16$
# - /usr/share/doc/dbus-1.12.16/AUTHORS.bz2
# - /usr/share/doc/dbus-1.12.16/ChangeLog.bz2
# - /usr/share/doc/dbus-1.12.16/NEWS.bz2
# - /usr/share/doc/dbus-1.12.16/README.bz2
# - /usr/share/doc/dbus-1.12.16/README.gentoo
# - /usr/share/doc/dbus-1.12.16/TODO.bz2
# - /usr/share/doc/dbus-1.12.16/examples
# - /usr/share/doc/dbus-1.12.16/examples/GetAllMatchRules.py.bz2
# - /usr/share/doc/dbus-1.12.16/examples/example-session-disable-stats.conf.bz2
# - /usr/share/doc/dbus-1.12.16/examples/example-system-enable-stats.conf.bz2
# - /usr/share/doc/dbus-1.12.16/html
# - /usr/share/doc/dbus-1.12.16/html/dbus-cleanup-sockets.1.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-daemon.1.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-faq.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-launch.1.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-monitor.1.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-run-session.1.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-send.1.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-specification.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-test-plan.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-test-tool.1.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-tutorial.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-update-activation-environment.1.html
# - /usr/share/doc/dbus-1.12.16/html/dbus-uuidgen.1.html
# - /usr/share/doc/dbus-1.12.16/html/diagram.png
# - /usr/share/doc/dbus-1.12.16/html/diagram.svg
# - /usr/share/doc/dbus-1.12.16/system-activation.txt.bz2
# - /usr/share/man$
# - /usr/share/man/man1$
# - /usr/share/man/man1/dbus-cleanup-sockets.1.bz2
# - /usr/share/man/man1/dbus-daemon.1.bz2
# - /usr/share/man/man1/dbus-launch.1.bz2
# - /usr/share/man/man1/dbus-monitor.1.bz2
# - /usr/share/man/man1/dbus-run-session.1.bz2
# - /usr/share/man/man1/dbus-send.1.bz2
# - /usr/share/man/man1/dbus-test-tool.1.bz2
# - /usr/share/man/man1/dbus-update-activation-environment.1.bz2
# - /usr/share/man/man1/dbus-uuidgen.1.bz2
# - /usr/share/xml$
# - /usr/share/xml/dbus-1$
# - /usr/share/xml/dbus-1/busconfig.dtd
# - /usr/share/xml/dbus-1/introspect.dtd
# - /var$
# - /var/lib$
# - /var/lib/dbus$
# - /var/lib/dbus/.keep_sys-apps_dbus-0


# Finalizer
- /patches$|/patches/.*

requires:
- category: "distro"
  name: "sabayon-desktop"
  version: ">=0.1"

steps:
#- bash rebuild_dracut.sh  (equo i first sabayon-dracut )
- mkdir /patches
- cp -rfv setup.sh /patches/live_setup.sh
- cp -rfv calamares.py /patches/calamares.py