unpack: true
includes:
# Kernel
- /boot$|/boot/.*
- /lib$
- /lib/firmware$|/lib/firmware/.*
- /lib/modules$|/lib/modules/.*
- /lib/modprobe.d$|/lib/modprobe.d/.*
requires:
- category: "distro"
  name: "sabayon-desktop"
  version: ">=0.1"
prelude:
- equo up
steps:
- ACCEPT_LICENSE=* equo i sys-kernel/linux-sabayon:5.6