unpack: true
includes:
- /bin$|/bin/.*

- /dev$|/dev/.*
- /etc$
# TODO: Add /etc to config protect
- /etc$|/etc/.*

- /home$|/home/.*
- /lib$|/lib.*
- /media$|/media/.*
- /mnt$|/mnt/.*
- /opt$|/opt/.*
- /root$|/root/.*
- /run$|/run/.*
- /sbin$|/sbin/.*
- /usr$|/usr/.*
- /var$|/var/.*
steps:
- equo up
- > 
  ACCEPT_LICENSE=* equo i
  @wireless
	app-admin/rigo
	app-arch/p7zip
	app-crypt/gnupg
	app-misc/sabayon-greeter
	app-crypt/pinentry-gtk2
	app-misc/calamares-sabayon
	app-office/libreoffice
	gnome-extra/nm-applet
	mate-base/mate
	mate-extra/mate-sensors-applet
	media-libs/libopenraw
	media-plugins/alsa-plugins
	media-sound/audacious
	media-video/mpv
	net-dialup/rp-pppoe
	net-irc/hexchat
	net-p2p/transmission-gtk
	x11-libs/gksu
	sys-apps/gnome-disk-utility
	sys-apps/usbutils
	sys-block/gparted
	sys-boot/os-prober
	sys-fs/ntfs3g
	sys-power/cpupower
	www-client/firefox
	x11-misc/magneto-gtk3
	x11-misc/mate-notification-daemon
	x11-misc/lightdm-base
	x11-misc/lightdm-slick-greeter
	x11-terms/guake
	x11-themes/gnome-themes-standard
	x11-themes/sabayon-artwork-core
	x11-themes/sabayon-artwork-grub
	x11-themes/sabayon-artwork-lightdm-slick-greeter
	x11-themes/sabayon-artwork-mate

- equo cleanup
- cp /etc/shadow /etc/shadow.defaults
- cp /etc/passwd /etc/passwd.defaults
- cp /etc/group /etc/group.defaults
- rm /var/log/entropy/entropy.log || true
requires:
- category: "distro"
  name: "sabayon-minimal-x"
  version: ">=0.1"
